version: '3'

networks:
  laravel:
    name: laravel
    external: true
    driver: bridge

services:
  nginx: 
    image: nginx:stable-alpine
    container_name: nginx_laravel_2
    ports: 
      - "8082:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - laravel

  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php_laravel_2
    volumes: 
      - ./src:/var/www/html
    ports: 
      - "9006:9006"
    networks: 
      - laravel
  
  composer:
    image: composer:latest
    container_name: composer_laravel_2
    volumes: 
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on: 
      - php
    networks: 
      - laravel

  artisan:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: artisan_laravel_2
    volumes: 
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks: 
      - laravel
    
