version: '3'

networks:
  laravel:
    name: laravel
    external: true

services:
  nginx: 
    image: nginx:stable-alpine
    container_name: nginx_laravel_2
    ports: 
      - "8082:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - laravel

  # mysql:
  #   image: mysql:5.7.29
  #   container_name: mysql_laravel_2
  #   restart: unless-stopped
  #   tty: true
  #   ports: 
  #     - "9306:3306"
  #   environment: 
  #     MYSQL_DATABASE: laravel_db
  #     MYSQL_USER: laravel_db
  #     MYSQL_PASSWORD: 123456789
  #     MYSQL_ROOT_PASSWORD: 123456789
  #     SERVICE_TAGS: dev
  #     SERVICE_NAME: mysql
  #   networks: 
  #     - laravel
  #   volumes: 
  #     - ./mysql:/var/lib/mysql
  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php_laravel_2
    volumes: 
      - ./src:/var/www/html
    ports: 
      - "9006:9006"
    networks: 
      - laravel
  
  composer:
    image: composer:latest
    container_name: composer_laravel_2
    volumes: 
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on: 
      - php
    networks: 
      - laravel
  
  # npm: 
  #   image: node:13.7
  #   container_name: npm_laravel_2
  #   volumes: 
  #     - ./src:/var/www/html
  #   working_dir: /var/www/html
  #   entrypoint: ['npm']

  artisan:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: artisan_laravel_2
    volumes: 
      - ./src:/var/www/html
    # depends_on: 
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks: 
      - laravel
    
